### ISSUE TITLE
Charset redstone wire client crash

### ISSUE THREAD

**Issue by CaptainPepperjack** [VazkiiModsArchive/Charset#11]
Here's the crash log http://pastebin.com/z5xVrY0H

**Comment by kingofrunes** [comment]
I'm also running into this problem on my 1.10.2 server. Everyone who's been joining my server has been running into the same error.

**Comment by jmcaffee** [comment]
Seeing the same thing [in this crash log](http://pastebin.com/rhqR4muf).

**ModPack:** All The Mods 1.10.2 v1.15
**Mod Version:** Charset v0.3.0 pre14

I had to use mcedit and remove one piece of redstone cable that 'went bad'.
