### ISSUE TITLE
[1.10.2] This mod no longer works

### ISSUE THREAD

**Issue by FiveEYZ** [VazkiiModsArchive/Charset#15]
tried to run it along with forge-1.10.2-12.18.1.2044-universal

but got this crash while launching
https://gist.github.com/FiveEYZ/732c61e670ec2003520a3125ab841351

**Comment by MakeLord95** [comment]
Dude, this is a duplicate of #13

**Comment by FiveEYZ** [comment]
im so sorry @MakeLord95

**Comment by MakeLord95** [comment]
Hey, np... Just pointing that out so @Vazkii wont get confused :P
