### ISSUE TITLE
Crash when breaking pipe with pickaxe

### ISSUE THREAD

**Issue by Inari-Whitebear** [VazkiiModsArchive/Charset#4]
Yeah, just crashing when I break a pipe with a pickaxe :/
https://gist.github.com/Inari-Whitebear/1629d362fed7d5742ae78ff4ca025443

**Comment by GirafiStudios** [comment]
@Inari-Whitebear, I gave a bit of an explanation here yesterday: https://github.com/CharsetMC/Charset/issues/81 :) I still think it is caused by MC Multipart.

**Comment by Inari-Whitebear** [comment]
Ah right, even says that in the multipart changelog... okay then :D
